adminUser:
  password: vault:pr-107-1abc/adminUser:password
  username: admin
dashboardAuthID: vault:pr-107-1abc:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:pr-107-1abc:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:pr-107-1abc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:pr-107-1abc/prow:hmacToken
